### ISSUE TITLE
Release of Python 3 compatible version

### ISSUE THREAD

**Issue by sallner** [FormAlchemy/pyramid_fanstatic#12]
This package has commits that make it Python 3 compatible since 6 years. It would be nice to have a proper release of the changes. 

@gawel @davidjb  Do you think that is possible?

Or is there some other package, which I am not aware of, that can be used nowadays for the fanstatic/pyramid integration?

**Comment by gawel** [comment]
Hi. I'm no longer maintaining those libraries. (I have no projects that uses them anymore) I can grant you access on github/pypi if you need changes/releases.

**Comment by sallner** [comment]
@gawel That would be nice, my username on PyPI is also sallner.

**Comment by gawel** [comment]
I've added you to the owner group on github. Only for this projet on pypi. Let me know if you need more.

**Comment by gawel** [comment]
And just so you know. All those project used to be released with https://pypi.org/project/zest.releaser/

Not sure it still works though. Maybe the latest version will complain about missing stuff.

**Comment by sallner** [comment]
I also use zest.releaser for my releases, so I am quite familiar. Thank you for the quick response.

**Comment by sallner** [comment]
I created a release on pypi, https://pypi.org/project/pyramid-fanstatic/0.6/ thanks for the help again!
